keep-network/local-setup

- README.adoc
- install-keep-dashboard.sh
- install.sh
- run-keep-dashboard.sh
The scripts can be used for Keep Dashboard installation and run.
To install the dashboard execute: `./install-keep-dashboard.sh`
To run the dasbhoard execute `./run-keep-dashboard.sh`
The install script is also a part of main `install.sh` and is executed after tBTC installation.
> Added scripts for Keep Dashboard installation

- .circleci/config.yml
Closes #8 
Depends on #12 
Here we introduce a CircleCI config that uses the appropriate provisioning scripts introduced by #12.
> CircleCI config for E2E tests execution

- install-tbtc-dapp.sh
- install-tbtc.sh
Changes made by https://github.com/keep-network/tbtc/pull/715 caused fails of the `install-tbtc.sh` script. This is because that pull request introduced a direct dependency on `keep-ecdsa` artifact from within `tbtc` contract migrations scripts. To repair the problem, a symlink to `keep-ecdsa` artifacts should be created before `tbtc` install script execution and the `package.json` file should point to the local `keep-ecdsa` instance.
> Symlink local keep-ecdsa artifacts for tBTC

- bitcoin/bitcoind/Dockerfile
- bitcoin/bitcoind/entrypoint.sh
- bitcoin/docker-compose.yml
- deployments/e2e-test/e2e-test-configmap.yml
- deployments/e2e-test/e2e-test-cronjob.yaml
- deployments/e2e-test/e2e-test-secret.yml.SAMPLE
- e2e/.dockerignore
- e2e/Dockerfile
- e2e/assertions.js
- e2e/common.js
- e2e/e2e-test.js
- e2e/package.json
Refs: https://github.com/keep-network/tbtc/issues/703
<s>Depends on: https://github.com/keep-network/tbtc.js/pull/58</s>
Here we modify the `e2e-test.js` script to enable the interaction with Keep testnet.
**Summary**
- Got rid of the direct dependency on Bitcoin RPC and stick to ElectrumX + bcoin library. This increases portability and allows us to run the script against both `local-setup` instances and testnet.
- Introduced manual construction of deposit transactions instead of use RPC's `sendtoaddress`. This opens new customization capabilities for future (e.g. test different types of transactions)
- Aligned `local-setup` scripts to keep the current functionality
- Externalized the configuration to command line parameters
- Introduced a `Dockerfile` which allows to build and run …
> Testnet-ready end-to-end test script

- e2e/e2e-test.js
- e2e/package-lock.json
Here we update the e2e test module to align with the latest changes in the system submodules. Specifically:
- Updated `package-lock.json` to reflect changes in the dependencies and make `npm install` pass
- Switched `deposit.getSatoshiLotSize` usage to the new name of this method
> E2E script updates

- deployments/e2e-test/e2e-test-configmap.yml
- deployments/e2e-test/e2e-test-cronjob.yaml
- e2e/e2e-test.js
Here we change several things around e2e cron job parameters:
- We enable passing the lot size as a script input instead of relying on a constant value.
- We set the cron to run every `8` hours instead of `4`
- We change the infura account used by the cron
- We set the lot size used by cron job to `1000000`
- We increased the `activeDeadlineSeconds` to `2` hours.
> E2E cron job parameters change

- .github/workflows/e2e-summary.yaml
This PR is related to e2e summary task where we fetch all created tbtc deposits on Ropsten and create a summary table. This change is to replace Infura endpoint (because of the limits) and frequency of running `e2e-summary.js` script
> Chaning infura endpoint, cron schedule and blocks timespan

- .github/workflows/e2e-summary.yaml
- e2e/e2e-summary.js
Allowing e2e test to continue with a report when it takes too much time to get the public key.
Adding improvements to html
Refs https://github.com/keep-network/tbtc/issues/703
> Skipping bitcoin address that takes too long too get and improvements

- .github/workflows/e2e-summary.yaml
Refs keep-network/tbtc#703
Infura threw "daily request count exceeded" error. In this PR we are replacing existing with a new one to run e2e summary report.
> Changing infura account because of daily request limits

- .github/workflows/e2e-summary.yaml
- e2e/e2e-summary.js
- Increasing blocks to 7500 (~24hour) which will result in search frame from: `currentBlock - 7500` to `currentBlock`
- Schedule job to run every 12th hour
- Iterating only through "ours" deposits that were run from `e2e-test.js`
> e2e report config

- deployments/e2e-test/e2e-test-cronjob.yaml
Improved timed out jobs replacement and changed the cron schedule to run every 4 hours.
Refs https://github.com/keep-network/tbtc/issues/703
> Tweak E2E cronjob parameters

- e2e/e2e-summary.js
Ref https://github.com/keep-network/tbtc/issues/703
If the public key was not set in the past 24hours, there is no need to hit contracts through Infura multiple times in the 3 sec [interval](https://github.com/keep-network/tbtc.js/blob/master/src/EthereumHelpers.js#L66). It can add up very quickly in e2e summary test and exceed the Infura's request limits which we observed earlier.
In this PR we give a 1 sec time to read a public key and if it is not there (meaning something was off), we move on to the next "Created" event.
This is the example report that can be generated through this script.
> Changing waiting time for getting bitcoin address and some cleanup

- e2e/e2e-summary.js
In this PR we are adding retries to retrieve redemption cost. This is just a "patch" to generate the report but the bigger issue is described [here](https://github.com/keep-network/tbtc.js/issues/72)
> Adding retries to get redemption cost

- e2e/Dockerfile
The most recent version of tbtc.js is `0.18.0-rc.2`. Updated end-to-end `Dockerfile` to point to that release.
> Updated tbtc.js version for end-to-end test Dockerfile

- inspector/.gitignore
- inspector/package-lock.json
- inspector/package.json
- inspector/scripts/inspect-operators.js
- inspector/truffle-config.js
Based on the list of nodes working in the network, the script inspects the status of beacon and ECDSA operators: their address, eligible stake, ETH operator account balance, and unbonded value (only for ECDSA operators).
Instructions:
1. Please fetch the node list from `/diagnostics` endpoint of a node, preferably a bootstrap node. Save ECDSA node list in `input-data/ecdsa-nodes.json` and beacon node list in `input-data/beacon-nodes.json`.
2. Run `npm install`.
3. Execute `ETH_HOSTNAME="<your_eth_host>" truffle exec ./scripts/inspect-operators.js --network mainnet`.
4. To output data in text-only mode, please set `OUTPUT_MODE` environment variable to `"text"`.
> Inspection script for network operators

- inspector/package-lock.json
- inspector/package.json
- inspector/scripts/inspect-beacon.js
Added supporting signatures field to the group summary prepared by the beacon inspection script. That information gives more context for DKG outcomes and can be useful while debugging DKG problems.
> Add signatures count to the beacon inspection script

- e2e/e2e-test.js
- install-tbtc.sh
- install.sh
Adding changes that should fix our e2e nightly test for deposits & redemption.
Successful build was tested on a parallel testing branch [here](https://app.circleci.com/pipelines/github/keep-network/local-setup/414/workflows/d9320b8f-dee6-4898-8875-f36018f0c72a/jobs/178)
> e2e nightly test fixes for CircleCI

- docs/auto-setup.adoc
This PR adds a tip to the auto-setup doc that informs to turn off an antivirus in case of an error while executing packer build command.
> Update auto-setup doc

- docs/auto-setup.adoc
After MacOS update to Big Sur version the vagrant setup didn't work
(SSH Port was not properly retrieved from SSHConfig). Problem can
be solved by execution of 'csrutil enable && reboot' command in the
Recovery Mode. Description of the solution added to the document.
> Adding troubleshooting section and another solution for vagrant error

- .gitignore
.envrc allows [direnv](https://direnv.net) to manage environment variables on a per-folder level, which is useful for managing environment variables across different repos (or different clones of the same repo).
For example, I can stick:
```
export GOPATH="/Users/beaushinkle/go"
```
in my `.envrc` (or whatever other environment variables specific to keep) in their relevant folders and it won't clutter my bash profile.
> Add .envrc to .gitignore

- install-keep-dashboard.sh
Calling `npm link` multiple times in one directory, for whatever reason,
unlinks all links and then only links the executed command. So:
```
npm link foo
npm link bar
```
will link foo, unlink `foo`, and then link `bar`. This leaves you with only
`bar` linked. To link both, we flatten the command:
```
npm link foo bar
```
tagging @Shadowfiend for review since we discovered it while getting my environment booted up
> Flatten the `npm link` Commands into One Line

- bitcoind-wallet/bin/cli.js
- bitcoind-wallet/index.js
- bitcoind-wallet/package-lock.json
- bitcoind-wallet/package.json
This creates a small package that exposes the `sendToAddress` and `getNewAddress` from [bitcoind-rpc](https://www.npmjs.com/package/bitcoind-rpc) to the command line so we can interact with the local bitcoin node. It automatically creates an `BitcoinRPC` instance using the [same config](https://github.com/keep-network/local-setup/blob/master/configs/bitcoin/config.json) from the e2e tests. In fact, it just wraps logic taken originally from the e2e test script. :)
To use, simply run `npm install -g <path-to-this-package>`. (Requires node version > 12.0)
Send:
```
$ bitcoind-wallet sendToAddress bcrt1q55zfnwqzjs76xknj5rhy5q5n85s6ctz2lvn03u 0.01
```
Get address:
```
$ bitcoind-wallet getNewAddress
```
Alternatively, we can just use the package …
> Add cli helper to send and receive btc from local btc node

- docs/manual-setup.adoc
Having the `$` is an indicator to the reader that those commands are
meant to be run in a bash-style shell, rather than some other repl or
anywhere else.
In #61, @Shadowfiend mentioned:
> At some point we should probably go ahead and make this change throughout the file, but for now let's roll with what we've got 🚢
No time like the present, so here it is :)
> Prefix Manual Setup Doc Shell Commands With $

- install-tbtc.sh
Prior to 0d9369ee4e398ee768d504605ee0606f5a4b57b4 in keep-ecdsa the initialization script operated by passing in command-line prompts via `read`. The aforementioned commit got rid of those in favor of argument flags, so we use those here.
tagging @Shadowfiend or @dimpar for review
> Update call from install-tbtc.sh to keep-ecdsa/scripts/initialize.sh

- docs/manual-setup.adoc
redux of #64 so I could edit it a bit!
The suggested node version in the manual setup doc is behind what we actually use, so this brings the doc up to date.
Tagging @Shadowfiend for review. Inspired by @dougvk :heart:
> Reflect Correct Node Version in manual-setup.adoc

- bitcoind-wallet/bin/cli.js
- bitcoind-wallet/index.js
These additional methods provide convenience around verifying the liquidation recovery flow. To test:
```
beaushinkle@Beaus-MBP ~> bitcoind-wallet getNewAddress
bcrt1qdw2xz0jntd7xwmgcrat483amspj55rwuq52vva
beaushinkle@Beaus-MBP ~> bitcoind-wallet getBalance bcrt1qdw2xz0jntd7xwmgcrat483amspj55rwuq52vva
0
beaushinkle@Beaus-MBP ~> bitcoind-wallet sendToAddress bcrt1qp5cps4cryf9fq958v7rez5jqzctswfml2z4y5q 2.3
beaushinkle@Beaus-MBP ~> bitcoind-wallet getBalance bcrt1qp5cps4cryf9fq958v7rez5jqzctswfml2z4y5q
2.3
```
```
beaushinkle@Beaus-MBP ~/l/t/s/scripts (master) [SIGINT]> curl -d '01000000000101fa42b57a4f75570a53889128db1a13b71dd553fd876269ca59987c46af5285810000000000000000000309cc320000000000160014a0aedee089b0cfa34e1e29c2dd2e618b19e8b95309cc320000000000160014f8c4e8695f8c2e0f598f8f00c2c4a83b17 …
```
> Add sendRawTransaction and getBalance

- .gitignore
- bitcoin/docker-compose.yml
This PR adds a new folder at `bitcoin/bitcoind/data` to the local project, and then configures that folder as a volume in the bitcoin docker. The result is that when we execute `./run-bitcoin.sh`, we now are able to natively view the block data:
```
beaushinkle@Beaus-MBP ~/l/b/bitcoind (expose-bitcoin-chain-data)> tree
.
├── Dockerfile
├── data
│   └── regtest
│       ├── banlist.dat
│       ├── bitcoind.pid
│       ├── blocks
│       │   ├── blk00000.dat
│       │   ├── index
│       │   │   ├── 000007.log
│       │   │   ├── CURRENT
│       │   │   ├── LOCK
│       │   │   └── MANIFEST-000006
│       │   └── rev00000.dat
│       ├── chainstate
│       │   ├── 000005.ldb
│       │   ├── 000008.log
│       │   ├── CURRENT
│       │   ├── LOCK
│       │   └── MANIFEST-000007
│       ├── …
```
> Expose the Bitcoin Block Data to the Host Machine

- .github/workflows/common-js.yml
Publishing of the common.js package has been switched off due to
problems with package versioning. Below configuration can succesfully
publish the package, but commiting of the information about bumped-up
version to the Git repository doesn't work - commiter's user name and
e-mail are required. Without this update of the version info, next runs
of the common-js-publish generate the same version of package as
before, and upload is not accepted. We may want to resolve that in the
future.
Possible approaches:
* swithing off git versionning (`--no-git-tag-version`) and creation of
action that checks the newest version of the common.js in the npm
registry and bumps the version up accordingly
* adding step that sets `user.email` and `user.name` global configs
before execution of the step …
> Turn off common.js publishing

- configs/keep-ecdsa/config.local.1.toml
- configs/keep-ecdsa/config.local.2.toml
- configs/keep-ecdsa/config.local.3.toml
Three main changes:
* We unify on 2-space tabs (I don't personally care here, just need for it to be consistent so I can tell my editor what to do)
* We move the TBTCSystem address to `ethereum.ContractAddresses.TBTCSystem` as per the deprecation warnings:
```
"TBTCSystem address configuration in SanctionedApplications.Addresses " +
"is DEPRECATED and will be removed. Please configure the " +
"TBTCSystem address alongside BondedECDSAKeep under " +
"Ethereum.ContractAddresses.",
```
* We add in a default-override for `TSS. PreParamsTargetPoolSize` to facilitate local development/testing. Having a higher number hurts iteration time and some machines will run out of memory or get cpu-locked trying to compute more pre-params.
> Modernize the keep-ecdsa Generated Config

- install-keep-core.sh
- install-keep-ecdsa.sh
- install-tbtc-dapp.sh
- install-tbtc.sh
The installation scripts can work with npm links instead of providing addresses of dependent external contracts in files like `external.js`.
Artifacts directory is created in installation script so we don't need to create it in the scripts in local-setup.
This code depends on couple of other PRs in the modules:
- https://github.com/keep-network/keep-core/pull/2452
- https://github.com/keep-network/keep-ecdsa/pull/776
- https://github.com/keep-network/tbtc/pull/790
> Refactor installation to use npm links and updated module's install scripts

- .git-blame-ignore-revs
- .prettierrc.yaml
- common.js/src/contracts.js
- common.js/test/contracts.test.js
- inspector/scripts/inspect-beacon.js
- inspector/scripts/inspect-ecdsa-keep.js
- inspector/scripts/inspect-operators.js
- inspector/scripts/inspect-tbtc.js
Our other projects don't include `trailingComma: "all"` in their prettier configs, so we remove it here and then re-run the prettier command.
This was the bottom of a rabbit hole, but I wanted to change `keep-ecdsa/solidity/scripts/lcl-client-config.js`. Changing that triggered the javascript linting job, which showed that there were a bunch of missing commas and wouldn't let me commit. I opened a separate PR to lint the ecdsa client: https://github.com/keep-network/keep-ecdsa/pull/779, but that PR didn't match with the lint reports from the linting job.
After a significant amount of debugging, it turns out that the linting job in github had a clean `.prettierrc`, and my development machine's ecdsa lint configuration was inheriting from this `local-setup`'s config. The near-term solution …
> Remove trailingComma: "all" from the prettier config

- deployments/local-setup-environment/provisioning/install-geth.sh
- docs/manual-setup.adoc
- run-geth.sh
In this PR we update the version of geth to 1.10.3-991384a7.
Geth command start API has changed in 1.10.3 so we need to tweak the names of passed arguments.
We also added more flags to geth run command to stabilize the private chain instance of the geth we're running.
Please see commits description for more details.
> Updated geth to 1.10.3-991384a7

- .github/workflows/e2e-local.yml
The step appending `GITHUB_PATH` with `/usr/local/go/bin` was
unnecessary. Only `GOPATH=$HOME/go` needs to be added to `GITHUB_PATH`.
> No longer append GITHUB_PATH with `/usr/local/go/bin`

- bitcoind-wallet/bin/cli.js
- bitcoind-wallet/index.js
bitcoind-rpc API allows selection of the address type to generate.
Options are: legacy, p2sh-segwit, and bech32. Default is bech32.
Here we enhance CLI command to let the user select the address type.
Ref: https://developer.bitcoin.org/reference/rpc/getnewaddress.html
> bitcoind-wallet: Let to select address type for getNewAddress

- .github/workflows/bitcoin.yml
In this PR we define a GH Actions workflow to validate the build of bitcoin images we use for the local environment.
Depends on https://github.com/keep-network/local-setup/pull/88
> Workflows to build docker images for bitcoin

- bitcoind-wallet/bin/cli.js
This PR implements the suggestions in https://github.com/keep-network/local-setup/pull/95#discussion_r652697412 which attempts to standardize our command list instructions with those presented in https://en.wikipedia.org/wiki/Usage_message and https://developers.google.com/style/code-syntax
Tagging @nkuba for review
> Reformat The Command List in bitcoind-wallet CLI

- .github/workflows/bitcoin.yml
- .github/workflows/common-js.yml
- docs/auto-setup.adoc
- docs/manual-setup.adoc
- inspector/package.json
Use of the `master` and `slave` terms in the computer industry is
widespread, but has been recently discouraged, as it was brought to
attention that the terms may be considered offensive.
GitHub has already moved their default repositories from the `master`
to `main` in many places. We're planning to do the same for our
repositories, this however requires some changes in the code.
After the proposed changes get merged to the `master` branch, the
repository should be ready for the migration from `master` to `main`.
To migrate from `master` to `main`:
1. Do a local branch rename with `git branch -m master main`
2. Push the renamed branch `git push -u origin main`
3. In the Github repo settings, rename the default branch: Settings ->
Branches -> Default branch -> (pencil icon) -> (change …
> Migrate from `master` to `main` branch

- configs/keep-ecdsa/config.local.1.toml
- configs/keep-ecdsa/config.local.2.toml
- configs/keep-ecdsa/config.local.3.toml
- docs/manual-setup.adoc
- initialize-bitcoin.sh
- install-keep-ecdsa.sh
This PR adds automation to the local `./install.sh` script to populate the keep-ecdsa configs with the relevant configuration bits for liquidation recovery. This allows developers to run a fully configured node for liquidation recovery. This will be mostly useless until either the liquidation-recovery-integration branch is merged in `keep-ecdsa` or if a developer is manually checking out that branch for local builds.
Tagging @nkuba for review
> Liquidation Recovery Config Automation

- bitcoind-wallet/bin/cli.js
Without the change, the `keep-ecdsa` startup during execution of `E2E
tests / Locally` workflow was failing with the following error:
```
/usr/bin/env: ‘node --experimental-modules
--experimental-json-modules’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
sed: can't read s/BENEFICIARY_ADDRESS//g: No such file or directory
```
> Fix the passing of options in shebang line

- .github/workflows/e2e-local.yml
- install-keep-ecdsa.sh
`E2E tests / Locally` workflow was failing due to incorrect syntax of `sed`
command in the install script for `keep-ecdsa` and due to too old version
of Go installed on the virtual machine. 
More context:
Syntax of the `sed -i` command is different for MacOS and for GNU
systems. The command in its old shape was failing when run on Ubuntu
(during execution of workflow with E2E tests). Fixed by merging the
problematic command with another sed command in the same file replacing
the text by using temporary file (instead of replacing in the current
file).
We're upgrading version of Go used in E2E tests local scripts to 1.16.6.
With previously used version building of keep-ecdsa client was failing
with `note: module requires Go 1.16` error.
It turned out that just changing the version of Go in …
> Fix issues with `sed` command and Go version in the E2E tests script

- .gitmodules
- deployments/local-setup-environment/provisioning/install-nodejs.sh
- docs/manual-setup.adoc
- install-applications.sh
- install-coverage-pools.sh
A script intalling coverage pools as part of installation of the system
has been added, because coverage pools are now required for successful
setup of the Token Dashboard.
A `coverage-pools` submodule needed to be added as part of this work.
> Incorporate coverage pools in local-setup

- docs/manual-setup.adoc
- install-e2e-test.sh
Up until recently, the `package-lock.json` in `keep-ecdsa/solidity` had
the `sha3` package configured in the `1.2.3` version. This version
wasn't working correctly with the Node.js 14.x which we're using for E2E
testing. This meant we needed to upgrade the `sha3` to a higher version.
Previously we've been doing that in the `install-e2e-test.sh` script,
but recently we upgraded the version (to `1.2.6`) directly in the
`keep-ecdsa/solidity/package-lock.json` file, making the `npm install
--save-dev sha3` step in the `install-e2e-test.sh` script obsolete.
Ref: https://github.com/keep-network/keep-ecdsa/pull/878
> No longer install `sha3` in a separate step

- .github/workflows/e2e-testnet.yml
We've changed the names of the secrets and need to update the workflow
configs accordingly. The change of secret name was introduced to
differentiate between WS and HTTP urls.
Depends on:
https://github.com/keep-network/local-setup/pull/98
Refs:
* https://github.com/keep-network/keep-core/pull/2548
*  https://github.com/keep-network/keep-ecdsa/pull/872
* https://github.com/keep-network/tbtc/pull/818
> Rename KEEP_TEST_ETH_HOSTNAME env variable

- run-geth.sh
The flag should not be set if we want to handle EIP155 transactions correctly.
This PR is a follow-up after https://github.com/keep-network/local-setup/pull/114.
> Remove rpc.allow-unprotected-txs for geth

- .github/workflows/bitcoin.yml
- .github/workflows/common-js.yml
The purpose of this PR is to set a cron job that would run tests and builds on a daily basis (at midnight) so the results can be displayed on Meercode dashboard.
> Adding cron for daily tests and builds on Mercode

- .github/workflows/bitcoin.yml
We do not need to validate external libs in daily builds. External libs should be compiled properly.
> Removing cron for bitcoin external libs

- .github/workflows/e2e-local.yml
Previously for part of the workflow we were using Node.js in version 12
and for part - version 14.17.0. Version 12 was needed because some of
the installed subprojects were built using v12. Now all subprojects are
built using v14, so we can use one common v14 for the whole workflow
with e2e tests.
> Bump up Node.js version used in the 'E2E / Locally' workflow to 14.17.0

- .github/workflows/format.yml
We have CI workflows scattered across various repositories. We try to keep their implementation as similar as possible. In this PR and the ones listed below we introduce a couple of changes which unify used solutions and fix small mistakes, such as:
* making tagging of published packages consistent
* passing `NPM_TOKEN` secret as variable instead of passing it by writing to file
* handling caching of npm/yarn dependencies via `setup-node` action
* adding `workflow_dispatch` job trigger where it's missing
* using Node.js in version 14.x instead of 12.x where possible
Related PRs in other repositories:
* https://github.com/keep-network/keep-core/pull/2776
* https://github.com/keep-network/keep-ecdsa/pull/941
* https://github.com/keep-network/tbtc/pull/842
* …
> Unify CI workflows

- e2e/common.js
With previous factor (`1.2`) E2E tests on Ropsten testnet were failing
with `undingError: Not enough funds. (available=0.0001236,
required=0.0001276)` error. In this commit we increase the factor to
`1.3` - with that value error is no longer occurring.
Closes #127.
> Increase amount of coins for covering the fee

- install-repositories.sh
We need to checkout `coverage-pools` at `6a9b084`, as after that commit
we introduced in the the `Asset Pool` contract a call to a `delegate`
function which is not present in the `KeepToken` contract used during
`AssetPool`'s deployment script.
Using latest code from `main` was causing error in the E2E tests on
local env., at the stage of running `05_deploy_asset_pool.ts` script
during installation of `coverage-pools`. Error was misleadingly
suggesting problems with gas estimation (`cannot estimate gas;
transaction may fail or may require manual gas limit`).
More details about the root cause:
- in PR 206 we introduced `delegate` function in `ICollateralToken`
https://github.com/keep-network/coverage-pools/blob/main/contracts/interfaces/ICollateralToken.sol#L30
- in the deployment script …
> Checkout specific SHA of cov-pools during installation of repositories

- .github/workflows/e2e-testnet.yml
After fixing some other issue causing E2E tests to fail we observed
that the test were still failing, this time with `execution reverted:
not at current or previous difficulty` error.
This is an error which we have seen in the past, happening for around
60% of jobs. Now we're seeing it for 100% of jobs, but we haven't run
many jobs so far since fixing that other issue. We want to increase the
frequency of tests execution to see if we will get some passing jobs
apart from those which fail.
> Increase frequency of running E2E tests on Testnet

- .github/workflows/e2e-local.yml
- .github/workflows/e2e-testnet.yml
- docs/manual-setup.adoc
The `tbtc.js` package contains a dependency to `@summa-tx/relay-sol@2.0.2`
package, which downloads one of its sub-dependencies via unathenticated
`git://` protocol. That protocol is no longer supported by GitHub. This
means that in certain situations installation of the package or update
of its dependencies using NPM may result in `The unauthenticated git
protocol on port 9418 is no longer supported` error or errors like
`ENOENT: no such file or directory, open
'/home/runner/work/local-setup/local-setup/e2e/node_modules/.staging/...'`.
That what was happening during execution of `e2e-local.yml` and
`e2e-testnet.yml. workflows.
As a workaround, we're adding to workflows a step which configures
Git to use `https://` protocol instead of `git://` when downloading
files.
More info: …
> Don't use unauthenticated git protocol

- .github/workflows/common-js.yml
- .github/workflows/e2e-local.yml
- .github/workflows/e2e-testnet.yml
The workflows that we're modifying in this PR were related to the `v1` of the system, which is no longer getting new functionalities. We don't need to execute these workflows every night / couple of hours.
> Cleanup of v1-related GH Actions workflows
